version: "3.0"

services:
  avahi:
    build: ./avahi
    network_mode: host

  homebridge:
    build: ./homebridge
    network_mode: host
    volumes:
      - ./homebridge/config:/home/config

  mqtt:
    image: eclipse-mosquitto
    command: ["/usr/sbin/mosquitto", "-v", "-c", "/mosquitto/config/mosquitto.conf"]
    ports:
      - "1883:1883"
